spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Yolo_Chef
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
