spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: public
jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: yolo-chef